development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username: tiennt
  password: 123

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: tiennt
  password: 123

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username: tiennt
  password: 123

cucumber:
  <<: *TEST